export default [
  {
    name: "Tulip",
    scientific_name: "Tulipa",
    colors: ["Red", "Yellow", "Purple", "Pink", "White"],
    season: "Spring",
    symbolism: "Elegance, Love, Prosperity",
  },
  {
    name: "Sunflower",
    scientific_name: "Helianthus",
    colors: ["Yellow", "Orange", "Red"],
    season: "Summer",
    symbolism: "Adoration, Loyalty, Longevity",
  },
  {
    name: "Lily",
    scientific_name: "Lilium",
    colors: ["White", "Pink", "Yellow", "Orange"],
    season: "Summer",
    symbolism: "Purity, Renewal, Passion",
  },
  {
    name: "Daisy",
    scientific_name: "Bellis perennis",
    colors: ["White", "Pink", "Yellow"],
    season: "Spring",
    symbolism: "Innocence, Purity, New Beginnings",
  },
  {
    name: "Orchid",
    scientific_name: "Orchidaceae",
    colors: ["Purple", "Pink", "White", "Yellow"],
    season: "Year-round",
    symbolism: "Luxury, Beauty, Strength",
  },
  {
    name: "Marigold",
    scientific_name: "Tagetes",
    colors: ["Orange", "Yellow", "Red"],
    season: "Summer",
    symbolism: "Creativity, Passion, Positivity",
  },
  {
    name: "Cherry Blossom",
    scientific_name: "Prunus serrulata",
    colors: ["Pink", "White"],
    season: "Spring",
    symbolism: "Renewal, Beauty, Transience of Life",
  },
  {
    name: "Hydrangea",
    scientific_name: "Hydrangea macrophylla",
    colors: ["Blue", "Pink", "White", "Purple"],
    season: "Summer",
    symbolism: "Gratitude, Understanding, Sincerity",
  },
  {
    name: "Iris",
    scientific_name: "Iris germanica",
    colors: ["Purple", "Blue", "White", "Yellow"],
    season: "Spring",
    symbolism: "Wisdom, Courage, Faith",
  },
  {
    name: "Peony",
    scientific_name: "Paeonia",
    colors: ["Pink", "White", "Red", "Yellow"],
    season: "Spring",
    symbolism: "Prosperity, Honor, Romance",
  },
];
