export default [
  {
    name: "Rose",
    scientific_name: "Rosa",
    colors: ["Red", "White", "Pink", "Yellow", "Orange"],
    season: "Spring",
    symbolism: "Love, Passion, Friendship",
  },
  {
    name: "Tulip",
    scientific_name: "Tulipa",
    colors: ["Red", "Yellow", "Pink", "Purple", "White"],
    season: "Spring",
    symbolism: "Perfect Love, Elegance",
  },
  {
    name: "Sunflower",
    scientific_name: "Helianthus",
    colors: ["Yellow", "Orange"],
    season: "Summer",
    symbolism: "Adoration, Loyalty",
  },
  {
    name: "Daisy",
    scientific_name: "Bellis perennis",
    colors: ["White", "Pink", "Yellow"],
    season: "Spring",
    symbolism: "Innocence, Purity",
  },
  {
    name: "Orchid",
    scientific_name: "Orchidaceae",
    colors: ["Pink", "Purple", "White", "Yellow"],
    season: "Year-round",
    symbolism: "Beauty, Strength, Love",
  },
  {
    name: "Lavender",
    scientific_name: "Lavandula",
    colors: ["Purple", "Blue"],
    season: "Summer",
    symbolism: "Serenity, Grace, Calmness",
  },
  {
    name: "Lily",
    scientific_name: "Lilium",
    colors: ["White", "Pink", "Yellow", "Orange"],
    season: "Summer",
    symbolism: "Purity, Devotion, Renewal",
  },
  {
    name: "Cherry Blossom",
    scientific_name: "Prunus serrulata",
    colors: ["Pink", "White"],
    season: "Spring",
    symbolism: "Renewal, Fleeting Beauty",
  },
  {
    name: "Peony",
    scientific_name: "Paeonia",
    colors: ["Pink", "Red", "White"],
    season: "Spring",
    symbolism: "Romance, Prosperity, Honor",
  },
  {
    name: "Marigold",
    scientific_name: "Tagetes",
    colors: ["Orange", "Yellow", "Red"],
    season: "Summer",
    symbolism: "Passion, Creativity, Warmth",
  },
];
